kumuluzee:
  name: ponudniki-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ponudniki
      connection-url: jdbc:postgresql://localhost:5432/ponudniki
      username: dbuser
      password: postgres
      pool:
        max-size: 2
  openapi-mp:
    enabled: true
    servlet:
      mapping: /openapi-spec
    scan:
      packages: si.fri.rso.skupina1.ponudniki.api.v1
    # servers:
    ui:
      mapping: /openapi
      server-auto-config:
        enabled: false
        original-uri-check: false
  health:
    servlet:
      mapping: /health
      enabled: true
    logs:
      enabled: true
      level: INFO
      period-s: 30
    checks:
      data-source-health-check:
        jndi-name: jdbc/ponudniki
        type: liveness
      http-health-check:
        - connection-url: http://localhost:8080/openapi
          type: readiness
        - connection-url: http://localhost:8080/v1/providers
          type: readiness
      disk-space-health-check:
        threshold: 100
        type: both
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="cdd0bbff-8f86-4910-ad4d-4ee50f6029b5-ls.logit.io"
                                    port="13921" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'
rest-properties:
  maintenance-mode: false
  broken: false
